USE master;
GO

IF NOT EXISTS (
	SELECT * 
	FROM SYS.DATABASES
	WHERE NAME = 'PHONEBOOK'
)
BEGIN

CREATE DATABASE PHONEBOOK
CONTAINMENT = NONE
ON PRIMARY ( 
	NAME = N'PHONEBOOK', 
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\PHONEBOOK.mdf' , 
	SIZE = 8192KB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 65536KB 
)
LOG ON ( 
	NAME = N'PHONEBOOK_LOG', 
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\PHONEBOOK_LOG.ldf' , 
	SIZE = 8192KB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 65536KB 
)
	PRINT N'New database was created.'
END
ELSE
	PRINT N'There already is a database.'

