USE PHONEBOOK;
GO

IF EXISTS(
	SELECT 1
	FROM sys.foreign_keys
	WHERE OBJECT_NAME(sys.foreign_keys.parent_object_id) = N'PERSONS'
	AND sys.foreign_keys.NAME = N'FK_PERSON_CITY_ID'
)
BEGIN
	ALTER TABLE PERSONS
	DROP CONSTRAINT FK_PERSON_CITY_ID
END

IF EXISTS(
	SELECT 1
	FROM sys.foreign_keys
	WHERE OBJECT_NAME(sys.foreign_keys.parent_object_id) = N'PHONE_NUMBERS'
	AND sys.foreign_keys.NAME = N'FK_PHONE_NUMBER_PERSON_ID'
)
BEGIN
	ALTER TABLE PHONE_NUMBERS
	DROP CONSTRAINT FK_PHONE_NUMBER_PERSON_ID
END

IF EXISTS(
	SELECT 1
	FROM sys.foreign_keys
	WHERE OBJECT_NAME(sys.foreign_keys.parent_object_id) = N'PHONE_NUMBERS'
	AND sys.foreign_keys.NAME = N'FK_PHONE_NUMBER_TYPE_ID'
)
BEGIN
	ALTER TABLE PHONE_NUMBERS
	DROP CONSTRAINT FK_PHONE_NUMBER_TYPE_ID
END

IF EXISTS (
	SELECT 1
	FROM sys.objects
	WHERE object_id = OBJECT_ID(N'CITIES')
	AND TYPE IN (N'U')
)
BEGIN
	DROP TABLE CITIES
END

IF EXISTS (
	SELECT 1
	FROM sys.objects
	WHERE object_id = OBJECT_ID(N'PHONE_TYPES')
	AND TYPE IN (N'U')
)
BEGIN
	DROP TABLE PHONE_TYPES;
END

IF EXISTS (
	SELECT 1
	FROM sys.objects
	WHERE object_id = OBJECT_ID(N'PERSONS')
	AND TYPE IN (N'U')
)
BEGIN
	DROP TABLE PERSONS;
END

IF EXISTS (
	SELECT 1
	FROM sys.indexes
	WHERE NAME = 'IX_PERSONS_CITY_ID'
	AND object_id = OBJECT_ID(N'PERSONS')
)
BEGIN
	DROP INDEX IX_PERSONS_CITY_ID
	ON PERSONS
END

IF EXISTS (
	SELECT 1
	FROM sys.objects
	WHERE object_id = OBJECT_ID(N'PHONE_NUMBERS')
	AND TYPE IN (N'U')
)
BEGIN
	DROP TABLE PHONE_NUMBERS;
END

IF EXISTS (
	SELECT 1
	FROM sys.indexes
	WHERE NAME = 'IX_PHONE_NUMBER_PERSON_ID'
	AND object_id = OBJECT_ID(N'PHONE_NUMBERS')
)
BEGIN
	DROP INDEX IX_PHONE_NUMBER_PERSON_ID
	ON PHONE_NUMBERS
END

IF EXISTS (
	SELECT 1
	FROM sys.indexes
	WHERE NAME = 'IX_PHONE_NUMBER_TYPE_ID'
	AND object_id = OBJECT_ID(N'PHONE_NUMBERS')
)
BEGIN
	DROP INDEX IX_PHONE_NUMBER_TYPE_ID
	ON PHONE_NUMBERS
END

PRINT N'Dropped tables: CITIES, PERSONS, PHONE_TYPES, PHONE_NUMBERS'
PRINT FORMAT(GETDATE(), 'dd-MM-yyyy HH:mm:ss')