USE PHONEBOOK
GO

IF EXISTS(
	SELECT *
	FROM sys.views
	WHERE name = N'ALL_DATA_VIEW'
)
	DROP VIEW ALL_DATA_VIEW
GO

BEGIN TRY
BEGIN TRANSACTION

IF (
	EXISTS (
		SELECT 1
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'CITIES')
		AND TYPE IN (N'U')
	)
	AND EXISTS (
		SELECT 1
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'PHONE_TYPES')
		AND TYPE IN (N'U')
	)
	AND EXISTS (
		SELECT 1
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'PERSONS')
		AND TYPE IN (N'U')
	)
	AND EXISTS (
		SELECT 1
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'PHONE_NUMBERS')
		AND TYPE IN (N'U')
	)
)
BEGIN
EXEC ('
		CREATE VIEW ALL_DATA_VIEW AS
	SELECT C.ID AS C_ID, C.UPDATE_COUNTER AS C_U_CNT, 
	C.CITY_NAME AS C_NAME, C.AREA AS C_AREA,
	P.ID AS P_ID, P.UPDATE_COUNTER AS P_U_CNT, P.FIRST_NAME AS P_F_NAME,
	P.MIDDLE_NAME AS P_M_NAME, P.LAST_NAME AS P_L_NAME, P.UCN AS P_UCN,
	P.CITY_ID AS P_C_ID, P.PERSON_ADDRESS AS P_ADDRESS,
	PN.ID AS PN_ID, PN.UPDATE_COUNTER AS PN_U_CNT, PN.PERSON_ID AS PN_P_ID,
	PN.PHONE_TYPE_ID AS PN_PT_ID, PN.PHONE_NUMBER AS PN_PHONE_NUMBER, 
	PT.ID AS PT_ID, PT.UPDATE_COUNTER AS PT_U_CNT, PT.PHONE_TYPE AS PT_PHONE_TYPE
	FROM CITIES C
	FULL OUTER JOIN PERSONS P
		ON C.ID = P.CITY_ID
	FULL OUTER JOIN PHONE_NUMBERS PN
		ON P.ID = PN.PERSON_ID
	FULL OUTER JOIN PHONE_TYPES PT
		ON PN.PHONE_TYPE_ID = PT.ID')
END
ELSE
BEGIN
	PRINT N'No such view found, or one of the tables is missing'
END

	
		

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH
GO

--CREATE VIEW ALL_DATA_VIEW AS
--SELECT C.ID AS C_ID, C.UPDATE_COUNTER AS C_U_CNT, 
--	C.CITY_NAME AS C_NAME, C.AREA AS C_AREA,
--	P.ID AS P_ID, P.UPDATE_COUNTER AS P_U_CNT, P.FIRST_NAME AS P_F_NAME,
--	P.MIDDLE_NAME AS P_M_NAME, P.LAST_NAME AS P_L_NAME, P.UCN AS P_UCN,
--	P.CITY_ID AS P_C_ID, P.PERSON_ADDRESS AS P_ADDRESS,
--	PN.ID AS PN_ID, PN.UPDATE_COUNTER AS PN_U_CNT, PN.PERSON_ID AS PN_P_ID,
--	PN.PHONE_TYPE_ID AS PN_PT_ID, PN.PHONE_NUMBER AS PN_PHONE_NUMBER, 
--	PT.ID AS PT_ID, PT.UPDATE_COUNTER AS PT_U_CNT, PT.PHONE_TYPE AS PT_PHONE_TYPE
--	FROM CITIES C
--	FULL OUTER JOIN PERSONS P
--		ON C.ID = P.CITY_ID
--	FULL OUTER JOIN PHONE_NUMBERS PN
--		ON P.ID = PN.PERSON_ID
--	FULL OUTER JOIN PHONE_TYPES PT
--		ON PN.PHONE_TYPE_ID = PT.ID
--GO