USE PHONEBOOK
GO

DECLARE @VAR_FIRST_NAME NCHAR(64);
DECLARE @VAR_MIDDLE_NAME NCHAR(64);
DECLARE @VAR_LAST_NAME NCHAR(64);
DECLARE @VAR_UCN NCHAR(32);
DECLARE @VAR_CITY_NAME NCHAR(64);
DECLARE @VAR_CITY_AREA NCHAR(64);
DECLARE @VAR_PERSON_ADDRESS NCHAR(512);

DECLARE @VAR_PHONE_TYPE NCHAR(32);
DECLARE @VAR_PHONE_NUMBER NCHAR(32);

SET @VAR_FIRST_NAME = N'Петър';
SET @VAR_MIDDLE_NAME = N'Петров';
SET @VAR_LAST_NAME = N'Петров';
SET @VAR_UCN = N'1815035454';
SET @VAR_CITY_NAME = N'Варна';
SET @VAR_CITY_AREA = N'Варна';
SET @VAR_PERSON_ADDRESS = N'Ул 305 Бл 2';

SET @VAR_PHONE_TYPE = N'Служебен';
SET @VAR_PHONE_NUMBER = N'+359223366883';

IF EXISTS (
	SELECT * 
	FROM PERSONS
	WHERE UCN = @VAR_UCN
)
	PRINT N'UCN not unique'

IF NOT EXISTS (
	SELECT * 
	FROM CITIES
	WHERE CITY_NAME = @VAR_CITY_NAME AND AREA = @VAR_CITY_AREA
)
	PRINT N'City not found'

IF NOT EXISTS (
	SELECT * 
	FROM PHONE_TYPES
	WHERE PHONE_TYPE = @VAR_PHONE_TYPE
)
	PRINT N'Invalid phone type'

IF EXISTS (
	SELECT * 
	FROM PHONE_NUMBERS
	WHERE PHONE_NUMBER = @VAR_PHONE_NUMBER
)
	PRINT N'Phone number not unique'


BEGIN TRY
BEGIN TRANSACTION

INSERT INTO PERSONS (
	[UPDATE_COUNTER],
	[FIRST_NAME],
	[MIDDLE_NAME],
	[LAST_NAME],
	[UCN],
	[CITY_ID],
	[PERSON_ADDRESS]
)
VALUES
(
	0, 
	@VAR_FIRST_NAME, 
	@VAR_MIDDLE_NAME, 
	@VAR_LAST_NAME, 
	@VAR_UCN, 
	(
	SELECT ID
	FROM CITIES 
	WHERE CITY_NAME = @VAR_CITY_NAME 
		AND AREA = @VAR_CITY_AREA
	),
	@VAR_PERSON_ADDRESS
)

INSERT INTO PHONE_NUMBERS (
	[UPDATE_COUNTER],
	[PERSON_ID],
	[PHONE_TYPE_ID],
	[PHONE_NUMBER]
)
VALUES
(
	0,
	(SELECT ID FROM PERSONS WHERE UCN = @VAR_UCN),
	(SELECT ID FROM PHONE_TYPES WHERE PHONE_TYPE = @VAR_PHONE_TYPE),
	@VAR_PHONE_NUMBER
)


	COMMIT TRANSACTION

END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH
GO