USE PHONEBOOK
GO

DECLARE @VAR_PHONE_TYPE NCHAR(32);
DECLARE @VAR_PHONE_NUMBER NCHAR(32);
DECLARE @VAR_UCN NCHAR(32);

SET @VAR_PHONE_TYPE = N'Служебен';
SET @VAR_PHONE_NUMBER = N'+359223366884';
SET @VAR_UCN = N'1815035454';

IF NOT EXISTS (
	SELECT * 
	FROM PHONE_TYPES
	WHERE PHONE_TYPE = @VAR_PHONE_TYPE
)
	PRINT N'Invalid phone type'

IF EXISTS (
	SELECT * 
	FROM PHONE_NUMBERS
	WHERE PHONE_NUMBER = @VAR_PHONE_NUMBER
)
	PRINT N'Phone number not unique'

IF NOT EXISTS (
	SELECT * 
	FROM PERSONS
	WHERE UCN = @VAR_UCN
)
	PRINT N'UCN not found'

BEGIN TRY
BEGIN TRANSACTION

INSERT INTO PHONE_NUMBERS (
	[UPDATE_COUNTER],
	[PERSON_ID],
	[PHONE_TYPE_ID],
	[PHONE_NUMBER]
)
VALUES
(
	0,
	(SELECT ID FROM PERSONS WHERE UCN = @VAR_UCN),
	(SELECT ID FROM PHONE_TYPES WHERE PHONE_TYPE = @VAR_PHONE_TYPE),
	@VAR_PHONE_NUMBER
)
	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH
GO