USE PHONEBOOK
GO

DECLARE @VAR_CITY_NAME NVARCHAR(64);
DECLARE @VAR_CITY_AREA NVARCHAR(64);

SET @VAR_CITY_NAME = N'София'
SET @VAR_CITY_AREA = N'София град'

IF NOT EXISTS (
	SELECT *
	FROM  CITIES
	WHERE CITY_NAME = @VAR_CITY_NAME 
		AND AREA = @VAR_CITY_AREA
)
PRINT N'No city with those names found'

BEGIN TRY
BEGIN TRANSACTION

IF NOT EXISTS (
	SELECT * 
	FROM PERSONS
	WHERE CITY_ID = (
		SELECT ID
		FROM  CITIES
		WHERE CITY_NAME = @VAR_CITY_NAME 
			AND AREA = @VAR_CITY_AREA
	)
)
DELETE FROM CITIES
WHERE CITY_NAME = @VAR_CITY_NAME 
	AND AREA = @VAR_CITY_AREA
ELSE
	PRINT N'Can not delete a city that has a person'

COMMIT TRANSACTION

END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH
GO