USE PHONEBOOK
GO

DECLARE @VAR_PHONE_TYPE NVARCHAR(32);

SET @VAR_PHONE_TYPE = N'СлужебенN'

IF NOT EXISTS (
	SELECT *
	FROM  PHONE_TYPES
	WHERE PHONE_TYPE = @VAR_PHONE_TYPE
)
PRINT N'No such phone type found'

BEGIN TRY
BEGIN TRANSACTION

IF NOT EXISTS (
	SELECT *
	FROM  PHONE_NUMBERS
	WHERE PHONE_TYPE_ID = 
		(
		SELECT ID
		FROM PHONE_TYPES
		WHERE PHONE_TYPE = @VAR_PHONE_TYPE
	)
)
DELETE FROM PHONE_TYPES
WHERE PHONE_TYPE = @VAR_PHONE_TYPE 
ELSE
	PRINT N'Can not delete a phone type that is a part from a phone number'

COMMIT TRANSACTION

END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH
GO